<a href="https://colab.research.google.com/github/parthnijh/gradient_descent/blob/main/gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib-inline

UsageError: Line magic function `%matplotlib-inline` not found.


In [ ]:
df=pd.read_csv("/content/drive/MyDrive/insurance_data/insurance_data.csv")
df

age  affordibility  bought_insurance
0    22              1                 0
1    25              0                 0
2    47              1                 1
3    52              0                 0
4    46              1                 1
5    56              1                 1
6    55              0                 0
7    60              0                 1
8    62              1                 1
9    61              1                 1
10   18              1                 0
11   28              1                 0
12   27              0                 0
13   29              0                 0
14   49              1                 1
15   55              1                 1
16   25              0                 1
17   58              1                 1
18   19              0                 0
19   18              1                 0
20   21              1                 0
21   26              0                 0
22   40              1                 1
23   45              1                 1
24   50              1                 1
25   54              1                 1
26   23              1                 0
27   46              1                 0

In [ ]:
from sklearn.model_selection import train_test_split
X=df.drop("bought_insurance",axis=1)
y=df["bought_insurance"]
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2,random_state=42)


In [56]:
Xtest.shape

(6, 2)

In [ ]:
Xtrainscaled=Xtrain.copy()
Xtrainscaled["age"]=Xtrainscaled["age"]/100

Xtestscaled=Xtest.copy()
Xtestscaled["age"]=Xtestscaled["age"]/100


In [ ]:
model=keras.Sequential(
    [
        keras.layers.Dense(1,input_shape=(2,),activation="sigmoid",kernel_initializer="ones",bias_initializer="zeros")
    ]
)

In [ ]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.fit(Xtrainscaled,ytrain,epochs=5000)

Streaming output truncated to the last 5000 lines.
Epoch 2501/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - accuracy: 0.8636 - loss: 0.5605
Epoch 2502/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.8636 - loss: 0.5605
Epoch 2503/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.8636 - loss: 0.5605
Epoch 2504/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.8636 - loss: 0.5604
Epoch 2505/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.8636 - loss: 0.5604
Epoch 2506/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.8636 - loss: 0.5603
Epoch 2507/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.8636 - loss: 0.5603
Epoch 2508/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - accuracy: 0.8636 - loss: 0.5603
Epoch 2509/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.8636 - loss: 0.5602
Epoch 2510/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 0.8636 - loss: 0.5602
Epoch 2511/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - accura

In [22]:
model.evaluate(Xtestscaled,ytest)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 348ms/step - accuracy: 1.0000 - loss: 0.2647


[0.26470306515693665, 1.0]

In [23]:
preds=model.predict(Xtestscaled)
preds

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step


array([[0.81626713],
       [0.75767535],
       [0.82367426],
       [0.18819512],
       [0.38559142],
       [0.19598222]], dtype=float32)

In [46]:
Xtestscaled


age  affordibility
9   0.61              1
25  0.54              1
8   0.62              1
21  0.26              0
0   0.22              1
12  0.27              0

In [24]:
coef,inercept=model.get_weights()

In [25]:
coef,inercept

(array([[5.018309 ],
        [1.1966311]], dtype=float32),
 array([-2.766541], dtype=float32))

In [26]:
##weights were 5.0 and 1.1 and bias was -2.7

In [27]:
import math
def sigmoid(x):
  return 1/(1+math.exp(-x))

In [31]:
def pred_function(age,affordability):
  weightedsum=coef[0]*age+coef[1]*affordability+inercept
  return sigmoid(weightedsum)


In [47]:
pred_function(.61,1)

/tmp/ipython-input-3748165616.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))


0.816267109586199

In [48]:
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [49]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [54]:
def grad_dec(age,affordability,y_true,epochs):
  w1=w2=1
  bias=0
  rate=0.5
  n=len(age)
  for i in range(epochs):
    weightedsum=w1*age+w2*affordability+bias
    ypred=sigmoid_numpy(weightedsum)
    loss=log_loss(y_true,ypred)
    bias_d=np.mean(ypred-y_true)
    w1d=(1/n)*np.dot(np.transpose(age),(ypred-y_true))
    w2d=(1/n)*np.dot(np.transpose(affordability),(ypred-y_true))
    bias=bias-rate*bias_d
    w1=w1-rate*w1d
    w2=w2-rate*w2d
    print(f"w1:{w1} w2{w2} bias {bias} loss {loss}")

  return w1,w2,bias







In [55]:
grad_dec(Xtrainscaled["age"],Xtrainscaled["affordibility"],ytrain,1000)

w1:0.9736899318847281 w20.931388810977659 bias -0.11748951666770448 loss 0.7428288579142563
w1:0.9536535852311094 w20.8740290167758512 bias -0.21881533456146035 loss 0.7072146449948488
w1:0.9393731039296969 w20.8271852202997496 bias -0.3053620401943441 loss 0.6814881914786812
w1:0.9301932588998061 w20.7897792032048467 bias -0.37884372361582785 loss 0.6633428084673968
w1:0.9254091137248938 w20.7605726653866934 bias -0.44108236820018304 loss 0.650742850709519
w1:0.9243325693598607 w20.738313053647322 bias -0.49384257986251556 loss 0.6420508089402462
w1:0.926333296357235 w20.7218280753843739 bias -0.5387319906498417 loss 0.6360356979531208
w1:0.930858097563688 w20.7100747303660235 bias -0.5771558825717441 loss 0.631816485354411
w1:0.9374354910317362 w20.7021560855322683 bias -0.6103083840841516 loss 0.6287844495353145
w1:0.9456716791005845 w20.6973185496313956 bias -0.639184616298235 loss 0.626529442944178
w1:0.9552423303850909 w20.6949390905593646 bias -0.6646027475198829 loss 0.62477998

(np.float64(8.401351862472232),
 np.float64(1.5008804215445002),
 np.float64(-4.382056927000268))